"""Add marked_paid_by to Pass

Revision ID: 04aca1be7792
Revises: 2b12a6958e6b
Create Date: 2025-04-12 09:29:13.189735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aca1be7792'
down_revision = '2b12a6958e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_paid_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.drop_column('marked_paid_by')

    # ### end Alembic commands ###
