"""Add AdminActionLog table

Revision ID: 0c0884ca241c
Revises: 4075162ff466
Create Date: 2025-04-19 11:02:11.938637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0884ca241c'
down_revision = '4075162ff466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_email', sa.String(length=150), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
