"""Create tables for user, activity, signup

Revision ID: 11041a3a9196
Revises: 04aca1be7792
Create Date: 2025-04-18 20:59:45.353004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11041a3a9196'
down_revision = '04aca1be7792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sessions_included', sa.Integer(), nullable=True),
    sa.Column('price_per_user', sa.Float(), nullable=True),
    sa.Column('goal_users', sa.Integer(), nullable=True),
    sa.Column('goal_revenue', sa.Float(), nullable=True),
    sa.Column('cost_to_run', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_url', sa.String(length=500), nullable=True),
    sa.Column('form_data', sa.Text(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('to_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('uses_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_dt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))


        batch_op.create_foreign_key('fk_pass_activity_id', 'activity', ['activity_id'], ['id'])
        batch_op.create_foreign_key('fk_pass_user_id', 'user', ['user_id'], ['id'])

        
        
        batch_op.drop_column('pass_created_dt')
        batch_op.drop_column('user_email')
        batch_op.drop_column('paid_ind')
        batch_op.drop_column('activity')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('games_remaining')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.alter_column('pass_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.alter_column('pass_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('games_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('activity', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid_ind', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('pass_created_dt', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paid')
        batch_op.drop_column('created_dt')
        batch_op.drop_column('uses_remaining')
        batch_op.drop_column('activity_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('to_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    op.drop_table('signup')
    op.drop_table('activity')
    op.drop_table('user')
    # ### end Alembic commands ###
