"""Add ebank_payment logging table

Revision ID: 28e19452dca1
Revises: ff55e02e0f58
Create Date: 2025-03-29 11:08:21.023858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e19452dca1'
down_revision = 'ff55e02e0f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebank_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('bank_info_name', sa.String(length=100), nullable=True),
    sa.Column('bank_info_amt', sa.Float(), nullable=True),
    sa.Column('matched_pass_id', sa.Integer(), nullable=True),
    sa.Column('matched_name', sa.String(length=100), nullable=True),
    sa.Column('matched_amt', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matched_pass_id'], ['pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebank_payment')
    # ### end Alembic commands ###
