"""Add payment_instructions to Activity

Revision ID: 4075162ff466
Revises: 4ede2cd88e9b
Create Date: 2025-04-19 09:59:01.525218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4075162ff466'
down_revision = '4ede2cd88e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('payment_instructions')

    # ### end Alembic commands ###
