"""Add ai_answer column to query_log table

Revision ID: 937a43599a19
Revises: a9e8d26b87b3
Create Date: 2025-11-20 13:37:48.275354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937a43599a19'
down_revision = 'a9e8d26b87b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.drop_column('ai_answer')

    # ### end Alembic commands ###
