"""Add from_email and mark_as_paid to EbankPayment

Revision ID: 9a2a78cc24a2
Revises: b0650e3be8b5
Create Date: 2025-03-29 12:43:41.632210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2a78cc24a2'
down_revision = 'b0650e3be8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebank_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('mark_as_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebank_payment', schema=None) as batch_op:
        batch_op.drop_column('mark_as_paid')
        batch_op.drop_column('from_email')

    # ### end Alembic commands ###
