"""Add activity column to Pass model

Revision ID: 9d3e0f489da0
Revises: cbffe846207a
Create Date: 2025-03-29 08:35:38.813847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3e0f489da0'
down_revision = 'cbffe846207a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.drop_column('activity')

    # ### end Alembic commands ###
