"""Add accounting-standard financial views (monthly_transactions_detail and monthly_financial_summary)

Revision ID: a9e8d26b87b3
Revises: af5045ed1c22
Create Date: 2025-11-19 20:42:00.896609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a9e8d26b87b3'
down_revision = 'af5045ed1c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed buggy op.drop_table('_alembic_tmp_activity') that was trying to drop non-existent table
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('email_templates',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('price_per_user')
        batch_op.drop_column('goal_users')
        batch_op.drop_column('payment_instructions')
        batch_op.drop_column('sessions_included')
        batch_op.drop_column('cost_to_run')

    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_chat_conversation_session_token', ['session_token'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_chat_usage_admin_date', ['admin_email', 'date'])

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'paid'"))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text("(STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'NOW'))"))
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('receipt_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'received'"))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_organizations_domain', ['domain'])

    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passport_pass_code'))
        batch_op.create_unique_constraint('uq_passport_pass_code', ['pass_code'])

    with op.batch_alter_table('passport_type', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index('ix_survey_activity', ['activity_id'], unique=False)
        batch_op.create_unique_constraint('uq_survey_survey_token', ['survey_token'])

    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_survey_response_response_token', ['response_token'])

    # Create accounting-standard financial views
    op.execute("""
        CREATE VIEW monthly_transactions_detail AS
        SELECT
            strftime('%Y-%m', COALESCE(p.paid_date, p.created_dt)) as month,
            a.name as project,
            'Income' as transaction_type,
            COALESCE(p.paid_date, p.created_dt) as transaction_date,
            'Passport Sales' as account,
            u.name as customer,
            NULL as vendor,
            p.notes as memo,
            p.sold_amt as amount,
            CASE WHEN p.paid = 1 THEN 'Paid' ELSE 'Unpaid (AR)' END as payment_status,
            'Passport System' as entered_by
        FROM passport p
        JOIN activity a ON p.activity_id = a.id
        LEFT JOIN user u ON p.user_id = u.id

        UNION ALL

        SELECT
            strftime('%Y-%m', i.date) as month,
            a.name as project,
            'Income' as transaction_type,
            i.date as transaction_date,
            i.category as account,
            NULL as customer,
            NULL as vendor,
            i.note as memo,
            i.amount,
            CASE
                WHEN i.payment_status = 'received' THEN 'Paid'
                WHEN i.payment_status = 'pending' THEN 'Unpaid (AR)'
                ELSE 'Unpaid (AR)'
            END as payment_status,
            COALESCE(i.created_by, 'System') as entered_by
        FROM income i
        JOIN activity a ON i.activity_id = a.id

        UNION ALL

        SELECT
            strftime('%Y-%m', e.date) as month,
            a.name as project,
            'Expense' as transaction_type,
            e.date as transaction_date,
            e.category as account,
            NULL as customer,
            NULL as vendor,
            e.description as memo,
            e.amount,
            CASE
                WHEN e.payment_status = 'paid' THEN 'Paid'
                WHEN e.payment_status = 'unpaid' THEN 'Unpaid (AP)'
                ELSE 'Unpaid (AP)'
            END as payment_status,
            COALESCE(e.created_by, 'System') as entered_by
        FROM expense e
        JOIN activity a ON e.activity_id = a.id

        ORDER BY month DESC, transaction_date DESC
    """)

    op.execute("""
        CREATE VIEW monthly_financial_summary AS
        WITH monthly_passports_cash AS (
            SELECT
                strftime('%Y-%m', paid_date) as month,
                activity_id,
                SUM(sold_amt) as passport_sales_cash
            FROM passport
            WHERE paid = 1 AND paid_date IS NOT NULL
            GROUP BY month, activity_id
        ),
        monthly_passports_ar AS (
            SELECT
                strftime('%Y-%m', COALESCE(paid_date, created_dt)) as month,
                activity_id,
                SUM(sold_amt) as passport_sales_ar
            FROM passport
            WHERE paid = 0
            GROUP BY month, activity_id
        ),
        monthly_income_cash AS (
            SELECT
                strftime('%Y-%m', date) as month,
                activity_id,
                SUM(amount) as other_income_cash
            FROM income
            WHERE payment_status = 'received'
            GROUP BY month, activity_id
        ),
        monthly_income_ar AS (
            SELECT
                strftime('%Y-%m', date) as month,
                activity_id,
                SUM(amount) as other_income_ar
            FROM income
            WHERE payment_status = 'pending'
            GROUP BY month, activity_id
        ),
        monthly_expenses_cash AS (
            SELECT
                strftime('%Y-%m', date) as month,
                activity_id,
                SUM(amount) as expenses_cash
            FROM expense
            WHERE payment_status = 'paid'
            GROUP BY month, activity_id
        ),
        monthly_expenses_ap AS (
            SELECT
                strftime('%Y-%m', date) as month,
                activity_id,
                SUM(amount) as expenses_ap
            FROM expense
            WHERE payment_status = 'unpaid'
            GROUP BY month, activity_id
        )
        SELECT
            COALESCE(pc.month, ic.month, ec.month, par.month, iar.month, eap.month) as month,
            a.id as activity_id,
            a.name as account,

            COALESCE(pc.passport_sales_cash, 0) as passport_sales,
            COALESCE(ic.other_income_cash, 0) as other_income,
            COALESCE(pc.passport_sales_cash, 0) + COALESCE(ic.other_income_cash, 0) as cash_received,
            COALESCE(ec.expenses_cash, 0) as cash_paid,
            (COALESCE(pc.passport_sales_cash, 0) + COALESCE(ic.other_income_cash, 0) - COALESCE(ec.expenses_cash, 0)) as net_cash_flow,

            COALESCE(par.passport_sales_ar, 0) as passport_ar,
            COALESCE(iar.other_income_ar, 0) as other_income_ar,
            COALESCE(par.passport_sales_ar, 0) + COALESCE(iar.other_income_ar, 0) as accounts_receivable,
            COALESCE(eap.expenses_ap, 0) as accounts_payable,

            (COALESCE(pc.passport_sales_cash, 0) + COALESCE(par.passport_sales_ar, 0) +
             COALESCE(ic.other_income_cash, 0) + COALESCE(iar.other_income_ar, 0)) as total_revenue,
            (COALESCE(ec.expenses_cash, 0) + COALESCE(eap.expenses_ap, 0)) as total_expenses,
            ((COALESCE(pc.passport_sales_cash, 0) + COALESCE(par.passport_sales_ar, 0) +
              COALESCE(ic.other_income_cash, 0) + COALESCE(iar.other_income_ar, 0)) -
             (COALESCE(ec.expenses_cash, 0) + COALESCE(eap.expenses_ap, 0))) as net_income

        FROM activity a
        LEFT JOIN monthly_passports_cash pc ON a.id = pc.activity_id
        LEFT JOIN monthly_passports_ar par ON a.id = par.activity_id AND COALESCE(pc.month, par.month) = par.month
        LEFT JOIN monthly_income_cash ic ON a.id = ic.activity_id AND COALESCE(pc.month, par.month, ic.month) = ic.month
        LEFT JOIN monthly_income_ar iar ON a.id = iar.activity_id AND COALESCE(pc.month, par.month, ic.month, iar.month) = iar.month
        LEFT JOIN monthly_expenses_cash ec ON a.id = ec.activity_id AND COALESCE(pc.month, par.month, ic.month, iar.month, ec.month) = ec.month
        LEFT JOIN monthly_expenses_ap eap ON a.id = eap.activity_id AND COALESCE(pc.month, par.month, ic.month, iar.month, ec.month, eap.month) = eap.month
        WHERE COALESCE(pc.month, par.month, ic.month, iar.month, ec.month, eap.month) IS NOT NULL
        ORDER BY month DESC, a.name
    """)

    # ### end Alembic commands ###


def downgrade():
    # Drop accounting-standard financial views
    op.execute("DROP VIEW IF EXISTS monthly_financial_summary")
    op.execute("DROP VIEW IF EXISTS monthly_transactions_detail")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_constraint('uq_survey_response_response_token', type_='unique')

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint('uq_survey_survey_token', type_='unique')
        batch_op.drop_index('ix_survey_activity')

    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('passport_type', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.drop_constraint('uq_passport_pass_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_passport_pass_code'), ['pass_code'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_organizations_domain', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'received'"))
        batch_op.alter_column('receipt_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("(STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'NOW'))"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'paid'"))

    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chat_usage_admin_date', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chat_conversation_session_token', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_to_run', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sessions_included', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('payment_instructions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('goal_users', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price_per_user', sa.FLOAT(), nullable=True))
        batch_op.alter_column('email_templates',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('goal_revenue', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_dt', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('email_templates', sqlite.JSON(), nullable=True),
    sa.Column('logo_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location_address_raw', sa.TEXT(), nullable=True),
    sa.Column('location_address_formatted', sa.TEXT(), nullable=True),
    sa.Column('location_coordinates', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
