"""Add ebank_payment fuzzy score

Revision ID: b0650e3be8b5
Revises: 28e19452dca1
Create Date: 2025-03-29 12:05:55.443093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0650e3be8b5'
down_revision = '28e19452dca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebank_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebank_payment', schema=None) as batch_op:
        batch_op.drop_column('name_score')

    # ### end Alembic commands ###
