"""Add status to Signup

Revision ID: c034707b5eef
Revises: 0c0884ca241c
Create Date: 2025-04-23 17:19:38.933552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c034707b5eef'
down_revision = '0c0884ca241c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_signup_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
