"""Add paid_date to Pass model

Revision ID: cbffe846207a
Revises: 9acb51f93162
Create Date: 2025-03-26 21:15:05.017825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbffe846207a'
down_revision = '9acb51f93162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.drop_column('paid_date')

    # ### end Alembic commands ###
