"""Initial schema - clean migration from production database

Revision ID: f4c10e5088aa
Revises: 
Create Date: 2025-11-14 11:20:22.033433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c10e5088aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_email', sa.String(length=150), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.create_index('ix_chat_conversation_admin', ['admin_email'], unique=False)
        batch_op.create_index('ix_chat_conversation_status', ['status'], unique=False)
        batch_op.create_index('ix_chat_conversation_token', ['session_token'], unique=False)

    op.create_table('chat_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_cents', sa.Integer(), nullable=True),
    sa.Column('provider_usage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email', 'date', name='uq_chat_usage_admin_date')
    )
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.create_index('ix_chat_usage_date', ['date'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('to_email', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('pass_code', sa.String(length=16), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('mail_server', sa.String(length=255), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_tls', sa.Boolean(), nullable=True),
    sa.Column('mail_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('mail_username', sa.String(length=255), nullable=True),
    sa.Column('mail_password', sa.String(length=500), nullable=True),
    sa.Column('mail_sender_name', sa.String(length=255), nullable=True),
    sa.Column('mail_sender_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fallback_to_system_email', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('original_question', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('execution_status', sa.String(length=20), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.create_index('ix_query_log_admin', ['admin_email'], unique=False)
        batch_op.create_index('ix_query_log_created', ['created_at'], unique=False)
        batch_op.create_index('ix_query_log_provider', ['ai_provider'], unique=False)
        batch_op.create_index('ix_query_log_status', ['execution_status'], unique=False)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email_templates', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('location_address_raw', sa.Text(), nullable=True),
    sa.Column('location_address_formatted', sa.Text(), nullable=True),
    sa.Column('location_coordinates', sa.String(length=100), nullable=True),
    sa.Column('goal_revenue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('query_result', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_conversation', ['conversation_id'], unique=False)
        batch_op.create_index('ix_chat_message_created', ['created_at'], unique=False)
        batch_op.create_index('ix_chat_message_type', ['message_type'], unique=False)

    op.create_table('survey_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('price_per_user', sa.Float(), nullable=True),
    sa.Column('sessions_included', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Float(), nullable=True),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass_code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=True),
    sa.Column('passport_type_name', sa.String(length=100), nullable=True),
    sa.Column('sold_amt', sa.Float(), nullable=True),
    sa.Column('uses_remaining', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('marked_paid_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_code')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('survey_token', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['survey_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_token')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index('ix_survey_activity', ['activity_id'], unique=False)
        batch_op.create_index('ix_survey_token', ['survey_token'], unique=False)

    op.create_table('ebank_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('from_email', sa.String(length=150), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('bank_info_name', sa.String(length=100), nullable=True),
    sa.Column('bank_info_amt', sa.Float(), nullable=True),
    sa.Column('matched_pass_id', sa.Integer(), nullable=True),
    sa.Column('matched_name', sa.String(length=100), nullable=True),
    sa.Column('matched_amt', sa.Float(), nullable=True),
    sa.Column('name_score', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('mark_as_paid', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('email_received_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_pass_id'], ['passport.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('date_used', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_url', sa.String(length=500), nullable=True),
    sa.Column('form_data', sa.Text(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.create_index('ix_signup_status', ['status'], unique=False)

    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('response_token', sa.String(length=32), nullable=False),
    sa.Column('responses', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_dt', sa.DateTime(), nullable=True),
    sa.Column('started_dt', sa.DateTime(), nullable=True),
    sa.Column('invited_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_token')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_index('ix_survey_response_survey', ['survey_id'], unique=False)
        batch_op.create_index('ix_survey_response_token', ['response_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_response_token')
        batch_op.drop_index('ix_survey_response_survey')

    op.drop_table('survey_response')
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_status')

    op.drop_table('signup')
    op.drop_table('reminder_log')
    op.drop_table('redemption')
    op.drop_table('ebank_payment')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_token')
        batch_op.drop_index('ix_survey_activity')

    op.drop_table('survey')
    op.drop_table('passport')
    op.drop_table('passport_type')
    op.drop_table('income')
    op.drop_table('expense')
    op.drop_table('user')
    op.drop_table('survey_template')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_type')
        batch_op.drop_index('ix_chat_message_created')
        batch_op.drop_index('ix_chat_message_conversation')

    op.drop_table('chat_message')
    op.drop_table('activity')
    op.drop_table('setting')
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.drop_index('ix_query_log_status')
        batch_op.drop_index('ix_query_log_provider')
        batch_op.drop_index('ix_query_log_created')
        batch_op.drop_index('ix_query_log_admin')

    op.drop_table('query_log')
    op.drop_table('organizations')
    op.drop_table('email_log')
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_usage_date')

    op.drop_table('chat_usage')
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_conversation_token')
        batch_op.drop_index('ix_chat_conversation_status')
        batch_op.drop_index('ix_chat_conversation_admin')

    op.drop_table('chat_conversation')
    op.drop_table('admin_action_log')
    op.drop_table('admin')
    # ### end Alembic commands ###
