"""Add notes to Pass

Revision ID: ff55e02e0f58
Revises: 9d3e0f489da0
Create Date: 2025-03-29 10:16:40.310528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55e02e0f58'
down_revision = '9d3e0f489da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
