#!/usr/bin/env python3
"""
Send test Interac-style payment email with Reply-To header

This script sends a properly formatted test email that mimics Interac e-Transfer
notifications, including a custom Reply-To header. This allows testing the
Reply-To extraction feature without sending real e-Transfers.

Usage:
    python test/send_test_payment_email.py

The script will prompt for: name, amount, and reply-to email.
Gmail credentials are hardcoded from .env file.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import sys

# Gmail SMTP Configuration (from .env)
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
SMTP_USER = 'kdresdell@gmail.com'
SMTP_PASSWORD = 'nvyd dtgy vohn zkuu'
DEFAULT_RECIPIENT = 'lhgi@minipass.me'


def format_amount(amount):
    """Format amount like Interac: 120,00 $ instead of 120.00 $"""
    return f"{amount:.2f}".replace('.', ',')


def create_interac_email_body(name, amount, message=""):
    """Create email body that mimics Interac format"""
    formatted_amount = format_amount(amount)

    body = f"""Virement Interac

{name} vous a envoyé {formatted_amount} $ (CAD)
"""

    if message:
        body += f"\nMessage : {message}\n"

    body += """
Pour déposer ces fonds, suivez les instructions ci-dessous.

Ceci est un courriel de test pour simuler un virement Interac.
Le système Minipass devrait extraire l'adresse Reply-To et l'utiliser
pour identifier l'expéditeur réel du paiement.

---
Test email generated by send_test_payment_email.py
"""

    return body


def send_test_email(name, amount, reply_to_email, message=""):
    """Send test payment email with Reply-To header"""

    # Create message
    msg = MIMEMultipart()
    msg['From'] = SMTP_USER
    msg['To'] = DEFAULT_RECIPIENT
    msg['Reply-To'] = reply_to_email  # KEY: This is what we're testing
    msg['Subject'] = f"Virement Interac : {name} vous a envoyé {format_amount(amount)} $"

    # Create body
    body = create_interac_email_body(name, amount, message)
    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    # Send via Gmail SMTP
    try:
        print("\n🔌 Connecting to Gmail SMTP...")
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()

        print("🔐 Authenticating...")
        server.login(SMTP_USER, SMTP_PASSWORD)

        print(f"📧 Sending to {DEFAULT_RECIPIENT}...")
        text = msg.as_string()
        server.sendmail(SMTP_USER, DEFAULT_RECIPIENT, text)
        server.quit()

        print("\n✅ Email sent!")
        print(f"\n📋 Details:")
        print(f"   From: {SMTP_USER}")
        print(f"   To: {DEFAULT_RECIPIENT}")
        print(f"   Reply-To: {reply_to_email}")
        print(f"   Subject: {msg['Subject']}")
        if message:
            print(f"   Message: {message}")

        print(f"\n🧪 Next Steps:")
        print(f"   1. Settings → Payment Bot → 'Run Payment Bot Now'")
        print(f"   2. Check Flask terminal for: 📧 Reply-To found: {reply_to_email}")
        print(f"   3. Go to /payment-bot-matches")
        print(f"   4. Verify email shows: {reply_to_email}")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)


def main():
    """Interactive test email sender"""
    print("=" * 70)
    print("Test Interac Payment Email Sender")
    print("=" * 70)
    print(f"\nSends to: {DEFAULT_RECIPIENT}")
    print(f"From: {SMTP_USER}\n")

    # Get inputs
    name = input("Sender name (e.g., 'Kenny Roger'): ").strip()
    if not name:
        print("❌ Name is required")
        sys.exit(1)

    amount_str = input("Amount (e.g., 120.00): ").strip()
    try:
        amount = float(amount_str)
        if amount <= 0:
            raise ValueError("Amount must be positive")
    except ValueError as e:
        print(f"❌ Invalid amount: {e}")
        sys.exit(1)

    reply_to_email = input("Reply-To email (e.g., 'kenny.roger@example.com'): ").strip()
    if not reply_to_email or '@' not in reply_to_email:
        print("❌ Valid email is required")
        sys.exit(1)

    message = input("Message (optional): ").strip()

    # Send email
    send_test_email(name, amount, reply_to_email, message)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Cancelled by user")
        sys.exit(0)
