"""Initial migration

Revision ID: 3fb6053a4bde
Revises: 
Create Date: 2025-03-21 16:37:50.754591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb6053a4bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass_code', sa.String(length=16), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('games_remaining', sa.Integer(), nullable=True),
    sa.Column('sold_amt', sa.Float(), nullable=True),
    sa.Column('pass_created_dt', sa.DateTime(), nullable=True),
    sa.Column('paid_ind', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_code')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass_id', sa.Integer(), nullable=False),
    sa.Column('date_used', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption')
    op.drop_table('setting')
    op.drop_table('pass')
    op.drop_table('admin')
    # ### end Alembic commands ###
